version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Budgy_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    image: akash879/ror:v1
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
