apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
spec:
  params:
    - name: IMAGE
      description: Docker image to build and push
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone
      taskRef:
        name: clone-repo
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-and-push
      taskRef:
        name: build-and-push
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      workspaces:
        - name: source
          workspace: shared-workspace
