apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
spec:
  params:
  - name: image-url
    description: "The URL of the Docker image to push"
  tasks:
  - name: build
    taskRef:
      name: kaniko-build
    params:
    - name: image-url
      value: "$(params.image-url)"
