apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
spec:
  params:
    - name: IMAGE
      description: The name of the image to push
      type: string
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=/workspace/source/Dockerfile"
        - "--context=/workspace/source/"
        - "--destination=$(params.IMAGE)"
  workspaces:
    - name: source
