apiVersion: v1
kind: Service
metadata:
  name: rails-app-service
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: rails-app
  type: ClusterIP


--- 

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
