apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rails-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Akash-879/RailsApp'
    targetRevision: HEAD
    path: kubernetes-manifests
  project: default
