apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-push-run
spec:
  pipelineRef:
    name: build-and-push-pipeline
  params:
    - name: IMAGE
      value: docker.io/akash879/rails:v2
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-workspace-pvc
