apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-push-pipeline-run-2
spec:
  pipelineRef:
    name: build-and-push-pipeline
  params:
  - name: image-url
    value: docker.io/akash879/rails:v2
